version: "3.8"
services:
  socket-proxy:
    image: tecnativa/docker-socket-proxy
    restart: unless-stopped
    volumes:
      -  /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      CONTAINERS: 1

  reverse-proxy:
    image: traefik:v2.8
    command:
      # Docker config
      - --providers.docker
      - --providers.docker.endpoint=tcp://socket-proxy:2375
      - --providers.docker.watch=true
      - --providers.docker.exposedbydefault=false
      # Entrypoints
      - --entryPoints.web.address=:80
    ports:
      - "80:80"
      - "443:443"

  db:
    image: mariadb:10.10.2
    command: "mysqld --character-set-server=utf8 --collation-server=utf8_general_ci"
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

  web:
    image: blopup/openmrs-referenceapplication:1.2.0
    environment:
      DB_DATABASE: ${DATABASE_NAME}
      DB_HOST: db
      DB_USERNAME: ${DATABASE_USERNAME}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      DB_CREATE_TABLES: "true" # change to 'true' if using an empty database
      DB_AUTO_UPDATE: "true" # change to 'true' if using an empty database
      MODULE_WEB_ADMIN: "true" # allow web admin on OpenMRS
    ports:
      - "8080:8080"
    labels:
      - traefik.enable=true
      - traefik.http.routers.web.rule=Host(`${DOMAIN}`)
    volumes:
      - type: bind
        source: ./legalConsentStore
        target: /opt/app/legalConsentStore
      - web-data:/usr/local/tomcat/.OpenMRS
      - /usr/local/tomcat/.OpenMRS/modules/ # used to mount persistent docker volume for modules
      - /usr/local/tomcat/.OpenMRS/owa/ # used to mount persistent docker volume for owa

volumes:
  db-data:
  web-data: