version: "3.8"
services:
  db:
    image: mariadb:10.10.2
    command: "mysqld --character-set-server=utf8 --collation-server=utf8_general_ci"
    environment:
      MYSQL_DATABASE: openmrs
      MYSQL_ROOT_PASSWORD: Admin123
      MYSQL_USER: openmrs
      MYSQL_PASSWORD: Admin123
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

  web:
    image: blopup/openmrs-referenceapplication:1.1.0
    depends_on:
      - db
    environment:
      DB_DATABASE: openmrs
      DB_HOST: db
      DB_USERNAME: openmrs
      DB_PASSWORD: Admin123
      DB_CREATE_TABLES: "true" # change to 'true' if using an empty database
      DB_AUTO_UPDATE: "true" # change to 'true' if using an empty database
      MODULE_WEB_ADMIN: "true" # allow web admin on OpenMRS
    ports:
      - "8080:8080"
    volumes:
      - web-data:/usr/local/tomcat/.OpenMRS
      - /usr/local/tomcat/.OpenMRS/modules/ # used to mount persistent docker volume for modules
      - /usr/local/tomcat/.OpenMRS/owa/ # used to mount persistent docker volume for owa

volumes:
  db-data:
  web-data: