version: '3.8'

services:
  web:
    environment:
      DB_USERNAME: ${DATABASE_USERNAME}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      DB_HOST: host.docker.internal
      DB_CREATE_TABLES: 'false'   # change to 'true' if using an empty database
      DB_AUTO_UPDATE: 'false'     # change to 'true' if using an empty database
      NEW_RELIC_ENVIRONMENT: "production"
    extra_hosts:
      - host.docker.internal:host-gateway