version: '3.8'

services:
  db:
    image: mariadb:10.10.2
    command: "mysqld --character-set-server=utf8 --collation-server=utf8_general_ci"
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

  web:
    environment:
      DB_HOST: db
      DB_USERNAME: ${DATABASE_USERNAME}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      DB_CREATE_TABLES: 'true'   # change to 'true' if using an empty database
      DB_AUTO_UPDATE: 'true'     # change to 'true' if using an empty database
      NEW_RELIC_ENVIRONMENT: "development"

volumes:
  db-data: