version: '3.8'

services:
  socket-proxy:
    image: tecnativa/docker-socket-proxy
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      CONTAINERS: 1

  reverse-proxy:
    image: traefik:v2.8
    command:
      # Docker config
      - --providers.docker
      - --providers.docker.endpoint=tcp://socket-proxy:2375
      - --providers.docker.watch=true
      - --providers.docker.exposedbydefault=false
      # Entrypoints
      - --entrypoints.web.address=:80
      # SSL
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.websecure.http.tls
      - --certificatesresolvers.blopupresolver.acme.storage=/acme/acme.json
      - --certificatesresolvers.blopupresolver.acme.httpchallenge.entrypoint=web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - reverse-proxy-data:/acme

  db:
    image: mariadb:10.10.2
    command: "mysqld --character-set-server=utf8 --collation-server=utf8_general_ci"
    environment:
      MYSQL_DATABASE: openmrs
      MYSQL_ROOT_PASSWORD: Admin123
      MYSQL_USER: openmrs
      MYSQL_PASSWORD: Admin123
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

  web:
    image: blopup/openmrs-referenceapplication:1.1.0
    environment:
      DB_DATABASE: openmrs
      DB_HOST: db
      DB_USERNAME: openmrs
      DB_PASSWORD: Admin123
      DB_CREATE_TABLES: 'true'   # change to 'true' if using an empty database
      DB_AUTO_UPDATE: 'true'     # change to 'true' if using an empty database
      MODULE_WEB_ADMIN: 'true'   # allow web admin on OpenMRS
    labels:
      - traefik.enable=true
      - traefik.http.routers.web.rule=Host(`${DOMAIN:-localhost}`)
      - traefik.http.routers.web.tls=true
      - traefik.http.routers.web.tls.certresolver=blopupresolver
    volumes:
      - web-data:/usr/local/tomcat/.OpenMRS
      - /usr/local/tomcat/.OpenMRS/modules/ # used to mount persistent docker volume for modules
      - /usr/local/tomcat/.OpenMRS/owa/     # used to mount persistent docker volume for owa

  config:
    image: blopup/blopup-config-server:2.0.0
    environment:
      GITHUB_USER: ${GITHUB_USER}
      GITHUB_PASSWORD: ${GITHUB_PASSWORD}
    ports:
      - "8081:8080"
    labels:
      - traefik.enable=true
      - traefik.http.routers.config.rule=Host(`${DOMAIN:-localhost}`) && PathPrefix(`/config`)
      - traefik.http.routers.config.middlewares=config-stripprefix
      - traefik.http.middlewares.config-stripprefix.stripprefix.prefixes=/config

volumes:
  db-data:
  web-data:
  reverse-proxy-data:
