# sample request to create a treatment on OpenMRS API
# A Treatment has a medication name, 0-5 drug families, recommendedBy, isActive
# To register a treatment, we use the Encounter and Observations model

###create encounter type (for treatment) - will respond with 400 because encounter type already exists in dev
# curl -X POST "https://blopup-dev.upc.edu/openmrs/ws/rest/v1/encountertype" -H  "accept: application/json" -H  "content-type: application/json" -d "{  \"name\": \"Treatment\",  \"description\": \"Encounter type to capture treatments recommended due to high blood pressure\"}"
POST https://blopup-dev.upc.edu/openmrs/ws/rest/v1/encountertype
accept: application/json
Content-Type: application/json
Authorization: Basic YWRtaW46QWRtaW4xMjM=

{
  "name": "Treatment",
  "description": "Encounter type to capture treatments recommended due to high blood pressure"
}

###create a new treatment encounter
# an encounter needs to be created before observations can be added
# an encounter is linked to a patient and a visit
# curl -X POST "https://blopup-dev.upc.edu/openmrs/ws/rest/v1/encounter" -H  "accept: application/json" -H  "content-type: application/json" -d "{}"
POST https://blopup-dev.upc.edu/openmrs/ws/rest/v1/encounter
accept: application/json
Content-Type: application/json
Authorization: Basic YWRtaW46QWRtaW4xMjM=

# you can include the list of observations in the request to create the encounter or you can create observations later and link with the encounter uuid
{
  "encounterProviders": [],
  "encounterType": "Treatment",
  "obs": [
    {
      "concept": "c1164da7-0b4f-490f-85da-0c4aac4ca8a1",
      "obsDatetime": "2023-12-12T13:24:26.374Z",
      "person": "bb227cef-0e4b-4dba-8448-d9bf3eefb154",
      "value": "Other"
    },
    {
      "concept": "43f8a8f3-6cf9-4a1f-bba5-8ec979f6d0b6",
      "obsDatetime": "2023-12-12T13:24:26.538Z",
      "person": "bb227cef-0e4b-4dba-8448-d9bf3eefb154",
      "value": "Cualquiera"
    },
    {
      "concept": "dfa881a4-5c88-4057-958b-f583c8edbdef",
      "obsDatetime": "2023-12-12T13:24:26.538Z",
      "person": "bb227cef-0e4b-4dba-8448-d9bf3eefb154",
      "value": "notes"
    },
    {
      "concept": "81f60010-961e-4bc5-aa04-435c7ace1ee3",
      "obsDatetime": "2023-12-12T13:24:26.538Z",
      "person": "bb227cef-0e4b-4dba-8448-d9bf3eefb154",
      "value": "1.0"
    },
    {
      "concept": "1a8f49cc-488b-4788-adb3-72c499108772",
      "encounter": "11f22661-d45a-42c5-9bec-5d9159ea68f0",
      "groupMembers": [
        {
          "concept": "1a8f49cc-488b-4788-adb3-72c499108772",
          "person": "bb227cef-0e4b-4dba-8448-d9bf3eefb154",
          "value": "a7fa1f5f-1ca3-4fe4-b02b-bd1dcc90201b"
        },
        {
          "concept": "1a8f49cc-488b-4788-adb3-72c499108772",
          "obsDatetime": "2023-12-12T13:24:27.665Z",
          "person": "bb227cef-0e4b-4dba-8448-d9bf3eefb154",
          "value": "f2c7ec86-6fe0-4e6a-bfe9-c73380228177"
        }
      ],
      "obsDatetime": "2023-12-12T13:24:27.664Z",
      "person": "bb227cef-0e4b-4dba-8448-d9bf3eefb154"
    }
  ],
  "patient": "bb227cef-0e4b-4dba-8448-d9bf3eefb154",
  "visit": "2dec3069-ec41-4685-9631-611a3a6427a1"
}
###create a new concept (observation type)
# concepts currently existing in dev for treatment are:
# 43f8a8f3-6cf9-4a1f-bba5-8ec979f6d0b6 - medication name - datatype = text
# c1164da7-0b4f-490f-85da-0c4aac4ca8a1 - recommended by - datatype = text
# 81f60010-961e-4bc5-aa04-435c7ace1ee3 - active - datatype = numeric (0 or 1)
# dfa881a4-5c88-4057-958b-f583c8edbdef - treatment notes = datatype = text
# 1a8f49cc-488b-4788-adb3-72c499108772 - drug families = datatype = coded (uuid for another concept)

# there are concepts for each of the medication types (see below for more details on how to create observations with multiple drug families)

# curl -X POST "https://blopup-dev.upc.edu/openmrs/ws/rest/v1/concept" -H  "accept: application/json" -H  "content-type: application/json" -d "{  \"names\": [    {      \"name\": \"Treatment\",      \"locale\": \"en\",      \"localePreferred\": true    }  ],  \"datatype\": \"Numeric\",  \"conceptClass\": \"Misc\",  \"set\": false}"
POST https://blopup-dev.upc.edu/openmrs/ws/rest/v1/concept
accept: application/json
Content-Type: application/json

{
  "names": [
    {
      "name": "Diuretics",
      "locale": "en",
      "localePreferred": true
    }
  ],
  "datatype": "Boolean",
  "conceptClass": "Misc",
  "set": false
}


###create treatment observation (example: medication name)
# change concept to the concept id of the observation type you want to create
# attach the concept to the treatment encountar through the encounter field
# curl -X POST "https://blopup-dev.upc.edu/openmrs/ws/rest/v1/obs" -H  "accept: application/json" -H  "content-type: application/json" -d "{}"
POST https://blopup-dev.upc.edu/openmrs/ws/rest/v1/obs
accept: application/json
Content-Type: application/json
Authorization: Basic YWRtaW46QWRtaW4xMjM=

{
  "person": "c20d8ab7-11e8-4d95-ab5d-e6d9c88be0c8",
  "concept": "43f8a8f3-6cf9-4a1f-bba5-8ec979f6d0b6",
  "obsDatetime": "2023-12-01T07:37:31.000+0000",
  "encounter": "b5ff03f3-02c5-444a-811a-9e51ef8f1ea0",
  "value": "Aspirin"
}

###create treatment observation for Recommended by
# curl -X POST "https://blopup-dev.upc.edu/openmrs/ws/rest/v1/obs" -H  "accept: application/json" -H  "content-type: application/json" -d "{}"
POST https://blopup-dev.upc.edu/openmrs/ws/rest/v1/obs
accept: application/json
Content-Type: application/json
Authorization: Basic YWRtaW46QWRtaW4xMjM=

{
  "person": "c20d8ab7-11e8-4d95-ab5d-e6d9c88be0c8",
  "concept": "c1164da7-0b4f-490f-85da-0c4aac4ca8a1",
  "encounter": "b5ff03f3-02c5-444a-811a-9e51ef8f1ea0",
  "obsDatetime": "2023-12-01T07:37:31.000+0000",
  "value": "BlopUp"
}

###create treatment observation for Active
# curl -X POST "https://blopup-dev.upc.edu/openmrs/ws/rest/v1/obs" -H  "accept: application/json" -H  "content-type: application/json" -d "{}"
POST https://blopup-dev.upc.edu/openmrs/ws/rest/v1/obs
accept: application/json
Content-Type: application/json
Authorization: Basic YWRtaW46QWRtaW4xMjM=

{
  "person": "c20d8ab7-11e8-4d95-ab5d-e6d9c88be0c8",
  "concept": "",
  "encounter": "b5ff03f3-02c5-444a-811a-9e51ef8f1ea0",
  "obsDatetime": "2023-12-01T09:37:31.000+0000",
  "value": 1
}

###create treatment observation for one medication type
# add the medication type  concept uuid to the value field
# existing medication types are:
# f2c7ec86-6fe0-4e6a-bfe9-c73380228177 - Beta Blockers
# 2146fbb8-8a8a-44f5-81de-2bee8ec4edce - Calcium Channel Blockers
# 162298AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA - Ace Inhibitors
# a7fa1f5f-1ca3-4fe4-b02b-bd1dcc90201b - Diuretics
# 162299AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA - Angiotensin Receptor Blockers
# curl -X POST "https://blopup-dev.upc.edu/openmrs/ws/rest/v1/obs" -H  "accept: application/json" -H  "content-type: application/json" -d "{}"
POST https://blopup-dev.upc.edu/openmrs/ws/rest/v1/obs
accept: application/json
Content-Type: application/json
Authorization: Basic YWRtaW46QWRtaW4xMjM=

{
  "person": "c20d8ab7-11e8-4d95-ab5d-e6d9c88be0c8",
  "concept": "1a8f49cc-488b-4788-adb3-72c499108772",
  "encounter": "b5ff03f3-02c5-444a-811a-9e51ef8f1ea0",
  "obsDatetime": "2023-12-01T09:37:31.000+0000",
  "value": "2146fbb8-8a8a-44f5-81de-2bee8ec4edce"
}

###create treatment observation for several Drug families
# add a list of observations with each drug family in the groupMembers field
# in this example, the medication recommended in the treatment is composed of both Beta Blockers and Calcium Channel Blockers
# curl -X POST "https://blopup-dev.upc.edu/openmrs/ws/rest/v1/obs" -H  "accept: application/json" -H  "content-type: application/json" -d "{}"
POST https://blopup-dev.upc.edu/openmrs/ws/rest/v1/obs
accept: application/json
Content-Type: application/json
Authorization: Basic YWRtaW46QWRtaW4xMjM=

{
  "person": "c20d8ab7-11e8-4d95-ab5d-e6d9c88be0c8",
  "concept": "1a8f49cc-488b-4788-adb3-72c499108772",
  "encounter": "b5ff03f3-02c5-444a-811a-9e51ef8f1ea0",
  "obsDatetime": "2023-12-01T09:37:31.000+0000",
  "groupMembers": [
    {
      "person": "c20d8ab7-11e8-4d95-ab5d-e6d9c88be0c8",
      "obsDatetime": "2023-12-01T09:37:31.000+0000",
      "encounter": "b5ff03f3-02c5-444a-811a-9e51ef8f1ea0",
      "concept": "1a8f49cc-488b-4788-adb3-72c499108772",
      "value": "f2c7ec86-6fe0-4e6a-bfe9-c73380228177"
    },
    {
      "person": "c20d8ab7-11e8-4d95-ab5d-e6d9c88be0c8",
      "obsDatetime": "2023-12-01T09:37:31.000+0000",
      "encounter": "b5ff03f3-02c5-444a-811a-9e51ef8f1ea0",
      "concept": "1a8f49cc-488b-4788-adb3-72c499108772",
      "value": "2146fbb8-8a8a-44f5-81de-2bee8ec4edce"
    }
  ]
}
