version: '3.8'

services:
  reverse-proxy:
    image: traefik:v2.8
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  db:
    image: ghcr.io/openmrstest/referenceapplication-db:latest
    build:
      context: ./
      dockerfile: ./db/Dockerfile
    command: "mysqld --character-set-server=utf8 --collation-server=utf8_general_ci"
    environment:
      MYSQL_DATABASE: openmrs
      MYSQL_ROOT_PASSWORD: Admin123
      MYSQL_USER: openmrs
      MYSQL_PASSWORD: Admin123
    volumes:
      - db-data:/var/lib/mysql

  web:
    build: generated/web
    image: ghcr.io/openmrstest/referenceapplication-server:latest
    depends_on:
      - db
    environment:
      DB_DATABASE: openmrs
      DB_HOST: db
      DB_USERNAME: openmrs
      DB_PASSWORD: Admin123
      DB_CREATE_TABLES: 'false'  # change to 'true' if using an empty database
      DB_AUTO_UPDATE: 'false'    # change to 'true' if using an empty database
      MODULE_WEB_ADMIN: 'true'   # allow web admin on OpenMRS
    labels:
      - traefik.http.routers.web.rule=Host("${DOMAIN}")
    volumes:
      - web-data:/usr/local/tomcat/.OpenMRS
      - /usr/local/tomcat/.OpenMRS/modules/ # used to mount persistent docker volume for modules
      - /usr/local/tomcat/.OpenMRS/owa/     # used to mount persistent docker volume for owa

volumes:
  db-data:
  web-data:
