name: Deploy to production environment

on:
  workflow_dispatch:

env:
  SSH_USER: ${{ secrets.SSH_USER }}
  ENV: blopup.upc.edu

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/remote.key
          chmod 600 ~/.ssh/remote.key
          cat >>~/.ssh/config <<END
          Host remote
            HostName $ENV
            User $SSH_USER
            IdentityFile ~/.ssh/remote.key
            StrictHostKeyChecking no
          END
        env:
          SSH_KEY: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
      - name: Create legalConsentStore folder
        run: |
          ssh remote mkdir -p legalConsentStore
      - name: Create docker .env file
        run: |
          echo "$ENV_FILE" > .env
        env:
          ENV_FILE: ${{ secrets.PROD_ENV_FILE }}
      - name: Copy deploy files to remote host
        run: |
          scp docker-compose.yml remote:/home/$SSH_USER
          scp docker-compose-prod.yml remote:/home/$SSH_USER
          scp .env remote:/home/$SSH_USER
      - name: Remove previous docker containers
        run: |
          scp safe-stop-container remote:/home/$SSH_USER
          ssh remote chmod +x safe-stop-container
          ssh remote ./safe-stop-container blopup-web-1
          ssh remote rm safe-stop-container
          ssh remote docker system prune -af --volumes
      - name: Deploy
        run: |
          ssh remote docker compose -f docker-compose.yml -f docker-compose-prod.yml -p blopup up -d --build
      - name: Remove sensitive files
        run: |
          ssh remote rm /home/$SSH_USER/.env