name: OpenMRS Pipeline

on:
  push:
    branches:
      - master
jobs:
  build-openmrs-distribution-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.2
    - name: Setup java version
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 8
    - name: Check maven version
      run: echo $(mvn --version)
    - name: Setup OpenMRS SDK
      run: mvn org.openmrs.maven.plugins:openmrs-sdk-maven-plugin:setup-sdk
    - name: Create docker distro
      run: mvn openmrs-sdk:build-distro -Ddistro=src/main/resources/openmrs-distro.properties -Ddir=docker
    - name: Run command
      run: echo $(cd docker && ls)
