name: OpenMRS Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - master
env:
  DOMAIN: ${{ secrets.DOMAIN }}

jobs:
  build-openmrs-distribution-file:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.2
    - name: Deploy to Docker host
      uses: wshihadeh/docker-deployment-action@v1
      with:
        remote_docker_host: deployment@${{ secrets.DOCKER_HOST }}
        ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
        ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
        deployment_mode: docker-compose
        stack_file_name: docker/docker-compose.yml
        args: docker
