name: OpenMRS Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - master
env:
  DOMAIN: ${{ secrets.DOMAIN }}

jobs:
  build-openmrs-distribution-file:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.2
    - name: Create .env file
      run: |
        echo "DOMAIN=\"$DOMAIN\"" >> .env
    - uses: alex-ac/github-action-ssh-docker-compose@master
      name: Docker-Compose Remote Deployment
      with:
        ssh_host: blopup.upc.edu
        ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
        ssh_user: deployment
        ssh_port: "22"
        docker_compose_prefix: blopup
