name: OpenMRS Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build-openmrs-distribution-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.2
    - name: Setup java version
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 8
    - name: Check maven version
      run: echo $(./mvnw --version)
    - name: Setup OpenMRS SDK
      run: printf '%s\n' n | ./mvnw org.openmrs.maven.plugins:openmrs-sdk-maven-plugin:setup-sdk
    - name: Create docker distro
      run: ./mvnw openmrs-sdk:build-distro -Ddistro=src/main/resources/openmrs-distro.properties -Ddir=docker/generated
    - name: Run command
      run: echo $(cd docker && ls)
    - name: Deploy to Docker host
      uses: wshihadeh/docker-deployment-action@v1
      with:
        remote_docker_host: ubuntu@${{ secrets.DOCKER_HOST }}
        ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
        ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
        deployment_mode: docker-swarm
        stack_file_name: docker/docker-compose.yml
        args: --publish published=8080,target=8080 docker